layout_spectrum: 1
color:
  saturation: 0.267536
  brandStrength: 0.4459491
  lightness: 0.7434369
  brandColors:
    - '#FFFFFF'
    - '#021F1F'
    - '#025CB4'
    - '#77BDBD'
    - '#0DCF5C'
  rhythmicContrast: 0.1347103
typography_spectrum: 1
name: Menlow Parker
